# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: Rome Wasn't Built in a Day!
- content: 罗马不是一天建成的，大牛不是一下练成的。
bottom_saying: Rome Wasn't Built in a Day!
# Content
excerpt_link: Read More
archive: 1
category: 1
tag: 1
rss: /atom.xml
#about: /www.baidu.com/
highlightjs: vs

#Works
works:
#- works_name: AAA
#  works_url: /
#- works_name: BBB
#  works_url: /atom.xml

#duoshuo name
#duoshuo: harrycheng

#disqus name
disqus_shortname:

#fancybox
fancybox: true

# Miscellaneous
github: https://github.com/harrycheng
twitter: https://twitter.com/hc_harrycheng
facebook: https://www.facebook.com/hc.harrycheng
google: https://github.com/harrycheng
weibo: https://weibo.com/u/1968948680

#about  timeline
timeline:

- num: 1
  word: "2021/9月 重拾Hexo 博客" 
- num: 2
  word: "2017/11月 进入机加工行业，从事机床物联网开发"
- num: 3
  word: "2014/04/15 开始在Github 搭建自己的私人博客，记录自己的经验，回馈大众"
- num: 4
  word: "2013/6月 大学毕业，从事数字媒体行业.NET开发 、Java开发、JS开发"

#Links
links:
- name: Kieran
  link: http://go.kieran.top/
- name: Cnblog
  link: http://www.cnblogs.com/harrycheng
  
 # Local search
# Dependencies: https://github.com/flashlab/hexo-generator-search
local_search:
  enable: false
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 2

